name: Compile Affinity Wine (To Releases)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: archlinux:multilib-devel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
       sudo pacman -Syu --noconfirm
       sudo pacman -Sy --noconfirm \
       alsa-lib alsa-plugins git cups desktop-file-utils dosbox ffmpeg fontconfig freetype2 gcc-libs gettext giflib gnutls \
       gst-plugins-base-libs gtk3 libgphoto2 libpcap libpulse libva libxcomposite libxcursor libxi libxinerama libxrandr \
       mingw-w64-gcc opencl-headers opencl-icd-loader samba sane sdl2 v4l-utils vulkan-icd-loader wine-mono \
       bzip2 capi20 curl flex krb5 libunwind libusb mesa p11-kit pcsclite smbclient wayland xz xkeyboard-config openal winetricks


    - name: Clone Wine repository
      run: |
        git clone https://gitlab.winehq.org/ElementalWarrior/wine.git ${{ github.workspace }}/ElementalWarrior-wine
        cd ${{ github.workspace }}/ElementalWarrior-wine
        git switch affinity-photo3-wine9.13-part3

    - name: Build Wine
      run: |
        CORES=$(nproc)
        mkdir -p ${{ github.workspace }}/winewow64-build/ ${{ github.workspace }}/wine-install/
        cd ${{ github.workspace }}/winewow64-build
        ${{ github.workspace }}/ElementalWarrior-wine/configure --prefix="${{ github.workspace }}/wine-install" --enable-archs=i386,x86_64
        
