name: Compile Affinity Wine (To Releases)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: archlinux:multilib-devel

    steps:
    - name: Install git
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -Sy --needed --noconfirm git

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo pacman -Sy --needed --noconfirm \
        alsa-lib alsa-plugins alsa-utils cups desktop-file-utils dosbox ffmpeg fontconfig freetype2 gcc-libs gettext giflib gnutls \
        gst-plugins-base-libs gtk3 libgphoto2 libpcap libpulse libva libxcomposite libxcursor libxi libxinerama libxrandr \
        mingw-w64-gcc opencl-headers opencl-icd-loader samba sane sdl2 v4l-utils vulkan-icd-loader wine-mono \
        bzip2 curl flex krb5 libunwind libusb mesa p11-kit pcsclite smbclient wayland xz xkeyboard-config openal winetricks \
        unixodbc

    - name: Clone Wine repository
      run: |
        git clone https://gitlab.winehq.org/ElementalWarrior/wine.git ${{ github.workspace }}/ElementalWarrior-wine
        cd ${{ github.workspace }}/ElementalWarrior-wine
        git switch affinity-photo3-wine9.13-part3

    - name: Build Wine
      run: |
        CORES=$(nproc)
        mkdir -p ${{ github.workspace }}/winewow64-build/ ${{ github.workspace }}/wine-install/
        cd ${{ github.workspace }}/winewow64-build
        ${{ github.workspace }}/ElementalWarrior-wine/configure --prefix="${{ github.workspace }}/wine-install" --enable-archs=i386,x86_64
        make --jobs $CORES
        make install

    - name: Cleanup
      run: |
        rm -rf ${{ github.workspace }}/winewow64-build
        rm -rf ${{ github.workspace }}/ElementalWarrior-wine

    - name: Verify Wine Installation
      run: |
        ls -la ${{ github.workspace }}/wine-install
        mv ${{ github.workspace }}/wine-install ${{ github.workspace }}/wine-affinity
        ln -s ${{ github.workspace }}/wine-affinity/bin/wine ${{ github.workspace }}/wine-affinity/bin/wine64

    - name: Archive Wine Installation
      run: tar -czvf ${{ github.workspace }}/wine-affinity.tar.gz -C ${{ github.workspace }}/wine-affinity/ .

    - name: Verify tarball creation
      run: ls -la ${{ github.workspace }}/wine-affinity.tar.gz
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Affinity-Wine-Build-${{ github.run_id }}
        path: ${{ github.workspace }}/wine-affinity.tar.gz

    - name: Upload To Releases
      uses: softprops/action-gh-release@v2
      with:
        files: /home/runner/work/affinity-wine-action/affinity-wine-action/wine-affinity.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ElementalWarrior-wine
        tag_name: affinity-photo3-wine9.13-part3
        draft: false
        prerelease: false
