name: Compile Affinity Wine (To Releases)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: archlinux:multilib-devel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a non-root user
      run: |
        useradd -m builduser
        echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        sudo -u builduser bash -c "whoami"

    - name: Install base-devel and git
      run: |
        sudo pacman -Sy --noconfirm git base-devel

    - name: Install yay (AUR helper)
      run: |
        sudo -u builduser bash -c "git clone https://aur.archlinux.org/yay.git"
        cd yay
        sudo -u builduser bash -c "cd yay && makepkg -si --noconfirm"

    - name: Install capi20 from AUR
      run: sudo -u builduser yay -S --noconfirm capi20

    - name: Install other dependencies
      run: |
        sudo pacman -Sy --noconfirm --needed \
          alsa-lib alsa-plugins cups desktop-file-utils dosbox ffmpeg fontconfig freetype2 gcc-libs gettext giflib gnutls \
          gst-plugins-base-libs gtk3 libgphoto2 libpcap libpulse libva libxcomposite libxcursor libxi libxinerama libxrandr \
          mingw-w64-gcc opencl-headers opencl-icd-loader samba sane sdl2 v4l-utils vulkan-icd-loader wine-mono \
          bzip2 curl flex krb5 libunwind libusb mesa p11-kit pcsclite smbclient wayland xz xkeyboard-config openal winetricks

    - name: Clone Wine repository
      run: |
        git clone https://gitlab.winehq.org/ElementalWarrior/wine.git ${{ github.workspace }}/ElementalWarrior-wine
        cd ${{ github.workspace }}/ElementalWarrior-wine
        git switch affinity-photo3-wine9.13-part3

    - name: Build Wine
      run: |
        CORES=$(nproc)
        mkdir -p ${{ github.workspace }}/winewow64-build/ ${{ github.workspace }}/wine-install/
        cd ${{ github.workspace }}/winewow64-build
        ${{ github.workspace }}/ElementalWarrior-wine/configure --prefix="${{ github.workspace }}/wine-install" --enable-archs=i386,x86_64
